version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=False
      - API_DEBUG=False
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./serviceAccountKey.json:/app/serviceAccountKey.json

volumes:
  redis_data: